<div>
    @if($lastSaleId)<div class="mb-5 flex items-center justify-between rounded-2xl border border-sky-200 bg-sky-50 p-4"><p class="text-sm font-semibold text-sky-800">Transaksi {{ $lastInvoice }} berhasil.</p><a class="btn-secondary" target="_blank" href="{{ route('sales.receipt',$lastSaleId) }}">Cetak struk</a></div>@endif
    @if(!$cashSession)
        <form method="post" action="{{ route('cash-sessions.open') }}" class="card mb-5 flex flex-wrap items-end gap-3">@csrf<div class="grid gap-1"><label>Modal awal kas</label><input name="opening_balance" type="number" min="0" value="0" required></div><button class="btn-primary">Buka sesi kasir</button><p class="text-sm text-amber-700">Sesi kasir wajib dibuka sebelum checkout.</p></form>
    @else
        <div class="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div><p class="font-bold text-emerald-900">Sesi kasir aktif</p><p class="text-sm text-emerald-700">Dibuka {{ $cashSession->opened_at->format('H:i') }} · Modal Rp {{ number_format($cashSession->opening_balance,0,',','.') }}</p></div><form method="post" action="{{ route('cash-sessions.close',$cashSession) }}" class="flex gap-2">@csrf<input name="closing_balance" type="number" min="0" placeholder="Kas fisik" required><button class="btn-secondary">Tutup sesi</button></form></div>
    @endif
    @error('cart')<p class="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $message }}</p>@enderror
    @error('cash_session')<p class="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $message }}</p>@enderror
    <div class="grid gap-5 xl:grid-cols-[1fr_420px]">
        <section><input wire:model.live.debounce.250ms="search" class="w-full" placeholder="Cari nama, SKU, atau scan barcode…"><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($products as $product)<button wire:click="addProduct({{ $product->id }})" class="card text-left transition hover:-translate-y-0.5 hover:border-brand-500"><div class="flex justify-between gap-2"><span class="badge">{{ $product->sku }}</span><span class="text-xs font-bold {{ $product->stock <= $product->minimum_stock ? 'text-red-600' : 'text-slate-500' }}">Stok {{ $product->stock }}</span></div><h3 class="mt-3 font-bold text-ink-900">{{ $product->name }}</h3><p class="mt-2 text-lg font-black text-brand-700">Rp {{ number_format($product->selling_price,0,',','.') }}</p></button>@endforeach</div></section>
        <aside class="card h-fit xl:sticky xl:top-5"><div class="flex items-center justify-between"><h2 class="text-xl font-black text-ink-900">Keranjang</h2><span class="badge">{{ count($cart) }} item</span></div><div class="mt-4 divide-y divide-slate-100">@forelse($cart as $item)<div class="py-4"><div class="flex justify-between gap-3"><div><p class="font-bold">{{ $item['name'] }}</p><p class="text-xs text-slate-500">Rp {{ number_format($item['price'],0,',','.') }}</p></div><button wire:click="remove({{ $item['id'] }})" class="text-xs font-bold text-red-600">Hapus</button></div><div class="mt-3 flex items-center justify-between"><div class="flex items-center gap-2"><button wire:click="decrement({{ $item['id'] }})" class="btn-secondary h-8 w-8 p-0">−</button><span class="w-7 text-center font-bold">{{ $item['quantity'] }}</span><button wire:click="addProduct({{ $item['id'] }})" class="btn-secondary h-8 w-8 p-0">+</button></div><strong>Rp {{ number_format($item['price']*$item['quantity'],0,',','.') }}</strong></div></div>@empty<p class="py-8 text-center text-sm text-slate-500">Pilih produk untuk mulai transaksi.</p>@endforelse</div>
            <div class="mt-4 space-y-3 border-t border-slate-200 pt-4"><div class="flex justify-between text-sm"><span>Subtotal</span><strong>Rp {{ number_format($subtotal,0,',','.') }}</strong></div><div class="grid gap-1"><label>Diskon transaksi</label><input wire:model.live.debounce.300ms="discount" type="number" min="0" max="{{ $subtotal }}"></div><div class="grid gap-1"><label>Metode pembayaran</label><select wire:model="paymentMethod"><option value="cash">Tunai</option><option value="transfer">Transfer</option><option value="qris">QRIS</option><option value="ewallet">E-wallet</option></select></div><div class="flex justify-between border-t border-slate-200 pt-4 text-xl"><span>Total</span><strong class="text-brand-700">Rp {{ number_format($total,0,',','.') }}</strong></div><button wire:click="checkout" wire:loading.attr="disabled" class="btn-primary w-full" @disabled(!$cashSession || !$cart)>Selesaikan transaksi</button></div>
        </aside>
    </div>
</div>
