'use client';
import { FormEvent, useEffect, useState } from 'react';

export default function StaffLoginPage(){
  const[accessRequired,setAccessRequired]=useState(true);const[pending,setPending]=useState(false);const[message,setMessage]=useState('');const[setup,setSetup]=useState<{token:string;secret:string;uri:string}|null>(null);
  useEffect(()=>{fetch('/backend/v1/staff/auth-config',{headers:{Accept:'application/json'}}).then(r=>r.json()).then(p=>setAccessRequired(Boolean(p.data.access_code_required))).catch(()=>{})},[]);
  function finish(payload:{data:{token:string;user:unknown}}){localStorage.setItem('ydc_staff_token',payload.data.token);localStorage.setItem('ydc_staff_user',JSON.stringify(payload.data.user));location.assign('/admin/dashboard')}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setMessage('');const data=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch('/backend/v1/staff/login',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({...data,device_name:`Next admin ${navigator.userAgent.slice(0,48)}`})});const payload=await response.json();if(!response.ok){setMessage(String(Object.values(payload.errors||{}).flat()[0]||payload.message));return}if(payload.data.requires_two_factor_setup){setSetup({token:payload.data.setup_token,secret:payload.data.secret,uri:payload.data.uri});return}finish(payload)}catch{setMessage('Koneksi ke Laravel terputus.')}finally{setPending(false)}}
  async function confirmSetup(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!setup)return;setPending(true);setMessage('');const data=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch('/backend/v1/staff/two-factor/setup',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({setup_token:setup.token,code:data.code})});const payload=await response.json();if(!response.ok){setMessage(String(Object.values(payload.errors||{}).flat()[0]||payload.message));return}finish(payload)}catch{setMessage('Koneksi ke Laravel terputus.')}finally{setPending(false)}}
  return <main className="staff-next-page"><section className="staff-login-shell"><aside className="staff-login-intro"><a className="staff-brand" href="/" aria-label="Younz Digital Center"><span><img src="/brand/younz-wordmark-inverse.svg" alt="" aria-hidden="true" /></span></a><p className="eyebrow eyebrow-light">Portal internal</p><h1>Akses operasional,<br/><em>tetap terlindungi.</em></h1><p>Ruang kerja khusus owner dan pegawai. Password, kode akses, dan autentikasi dua faktor diverifikasi langsung oleh Laravel.</p><ol><li><b>01</b><span><strong>Akses sesuai peran</strong><small>Menu mengikuti wewenang akun.</small></span></li><li><b>02</b><span><strong>Wajib 2FA</strong><small>Kode autentikator enam digit.</small></span></li><li><b>03</b><span><strong>Aktivitas tercatat</strong><small>Login penting masuk audit keamanan.</small></span></li></ol></aside>{setup?<form className="staff-login-card" onSubmit={confirmSetup}><p className="eyebrow">Aktivasi keamanan</p><h2>Hubungkan authenticator</h2><p>Tambahkan secret berikut ke Google Authenticator, Microsoft Authenticator, 1Password, atau aplikasi TOTP lain.</p>{message&&<div className="form-error">{message}</div>}<label>Secret manual<code className="staff-setup-secret">{setup.secret}</code></label><details className="staff-setup-uri"><summary>URI konfigurasi</summary><code>{setup.uri}</code></details><label>Kode 6 digit<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required autoComplete="one-time-code"/></label><button className="button button-dark full-button" disabled={pending}>{pending?'Mengaktifkan…':'Aktifkan 2FA & masuk'}</button><button className="staff-setup-back" type="button" onClick={()=>{setSetup(null);setMessage('')}}>Kembali ke login</button></form>:<form className="staff-login-card" onSubmit={submit}><p className="eyebrow">Portal pegawai</p><h2>Masuk ke dashboard</h2><p>Gunakan akun aktif yang dibuat owner.</p>{message&&<div className="form-error">{message}</div>}{accessRequired&&<label>Kode akses internal<input name="access_code" type="password" required autoComplete="off"/></label>}<label>Email pegawai<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><label>Kode autentikator <small>Kosongkan jika belum pernah mengaktifkan 2FA.</small><input name="two_factor_code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code"/></label><button className="button button-dark full-button" disabled={pending}>{pending?'Memverifikasi…':'Masuk sebagai pegawai'}</button><small>Login pertama akan memandu aktivasi authenticator.</small><a href="/akun/masuk">Masuk sebagai pelanggan</a></form>}</section></main>;
}
