<?php
namespace App\Http\Controllers;
use App\Models\Customer;use App\Models\Supplier;use App\Support\AuditLogger;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;
class StaffDirectoryApiController extends Controller{
public function __construct(private readonly AuditLogger $audit){}
public function suppliers(Request $request):JsonResponse{$this->authorizeSuppliers($request);$items=Supplier::query()->withCount('products')->when($request->string('q')->toString(),fn($q,string $term)=>$q->where('name','like',"%{$term}%"))->latest()->paginate(20)->withQueryString();return response()->json(['data'=>['suppliers'=>collect($items->items())->map(fn(Supplier $s)=>['id'=>$s->id,'name'=>$s->name,'contact_name'=>$s->contact_name,'phone'=>$s->phone,'email'=>$s->email,'address'=>$s->address,'is_active'=>$s->is_active,'products_count'=>$s->products_count])->values(),'pagination'=>['current_page'=>$items->currentPage(),'last_page'=>$items->lastPage(),'total'=>$items->total()]]]);}
public function storeSupplier(Request $request):JsonResponse{$this->authorizeSuppliers($request);$data=$request->validate(['name'=>['required','string','max:150'],'contact_name'=>['nullable','string','max:150'],'phone'=>['nullable','string','max:30'],'email'=>['nullable','email'],'address'=>['nullable','string'],'is_active'=>['nullable','boolean']]);$supplier=Supplier::create([...$data,'is_active'=>$request->boolean('is_active',true)]);$this->audit->log('supplier.created',$supplier,after:$supplier->toArray());return response()->json(['message'=>'Supplier berhasil ditambahkan.','data'=>['id'=>$supplier->id,'name'=>$supplier->name]],201);}
public function customers(Request $request):JsonResponse{$this->authorizeCustomers($request);$items=Customer::query()->withCount(['sales','serviceOrders'])->when($request->string('q')->toString(),fn($q,string $term)=>$q->where(fn($q)=>$q->where('name','like',"%{$term}%")->orWhere('phone','like',"%{$term}%")->orWhere('email','like',"%{$term}%")))->latest()->paginate(20)->withQueryString();return response()->json(['data'=>['customers'=>collect($items->items())->map(fn(Customer $c)=>['id'=>$c->id,'name'=>$c->name,'phone'=>$c->phone,'email'=>$c->email,'address'=>$c->address,'type'=>$c->type,'notes'=>$c->notes,'sales_count'=>$c->sales_count,'orders_count'=>$c->service_orders_count])->values(),'types'=>collect(['umum','pelajar','guru','sekolah','kantor','umkm','instansi','pelanggan_tetap'])->map(fn($v)=>['code'=>$v,'label'=>str($v)->replace('_',' ')->title()->toString()])->values(),'pagination'=>['current_page'=>$items->currentPage(),'last_page'=>$items->lastPage(),'total'=>$items->total()]]]);}
public function storeCustomer(Request $request):JsonResponse{$this->authorizeCustomers($request);$data=$request->validate(['name'=>['required','string','max:150'],'phone'=>['nullable','string','max:30'],'email'=>['nullable','email','max:150'],'address'=>['nullable','string','max:1000'],'type'=>['required','in:umum,pelajar,guru,sekolah,kantor,umkm,instansi,pelanggan_tetap'],'notes'=>['nullable','string','max:1000']]);$customer=Customer::create($data);$this->audit->log('customer.created',$customer,after:$customer->toArray());return response()->json(['message'=>'Pelanggan berhasil ditambahkan.','data'=>['id'=>$customer->id,'name'=>$customer->name]],201);}
private function authorizeSuppliers(Request $request):void{abort_unless($request->user()->isStaff()&&$request->user()->tokenCan('staff:suppliers')&&$request->user()->hasRole('owner','admin'),403);}
private function authorizeCustomers(Request $request):void{abort_unless($request->user()->isStaff()&&$request->user()->tokenCan('staff:customers')&&$request->user()->hasRole('owner','admin','cashier'),403);}}