<?php
namespace App\Http\Controllers;
use App\Actions\Approvals\ApprovalEngine;use App\Enums\ApprovalStatus;use App\Models\ApprovalRequest;use App\Models\DigitalTransaction;use App\Models\Product;use App\Models\User;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
class StaffApprovalApiController extends Controller{
public function index(Request $request):JsonResponse{$this->authorizeAccess($request);$status=$request->query('status');if($status!==null&&$status!=='')validator(['status'=>$status],['status'=>[Rule::enum(ApprovalStatus::class)]])->validate();$items=ApprovalRequest::query()->with(['requester:id,name','decider:id,name','refund.sale:id,invoice_number','subject'])->when($status,fn($q)=>$q->where('status',$status))->orderByRaw("CASE WHEN status = 'pending' THEN 0 ELSE 1 END")->latest('requested_at')->paginate(20)->withQueryString();return response()->json(['data'=>['approvals'=>collect($items->items())->map(fn(ApprovalRequest $a)=>$this->summary($a))->values(),'statuses'=>collect(ApprovalStatus::cases())->map(fn($s)=>['code'=>$s->value,'label'=>$s->label()])->values(),'pagination'=>['current_page'=>$items->currentPage(),'last_page'=>$items->lastPage(),'total'=>$items->total()]]]);}
public function show(Request $request,ApprovalRequest $approval):JsonResponse{$this->authorizeAccess($request);$approval->load(['requester:id,name,role','decider:id,name','events.actor:id,name','subject','refund.sale:id,invoice_number','refund.items.saleItem:id,name']);$subject=match(true){$approval->subject instanceof Product=>$approval->subject->name,$approval->subject instanceof User=>$approval->subject->name,$approval->subject instanceof DigitalTransaction=>$approval->subject->transaction_number,default=>null};return response()->json(['data'=>[...$this->summary($approval),'reason'=>$approval->reason,'decision_notes'=>$approval->decision_notes,'subject'=>$subject,'payload'=>$approval->payload,'refund'=>$approval->refund?['refund_number'=>$approval->refund->refund_number,'invoice_number'=>$approval->refund->sale?->invoice_number,'amount'=>$approval->refund->amount,'items'=>$approval->refund->items->map(fn($i)=>['name'=>$i->saleItem->name,'quantity'=>$i->quantity,'amount'=>$i->amount,'restore_stock'=>$i->restore_stock])->values()]:null,'events'=>$approval->events->map(fn($e)=>['status'=>['code'=>$e->to_status,'label'=>ApprovalStatus::tryFrom($e->to_status)?->label()??str($e->to_status)->headline()->toString()],'actor'=>$e->actor?->name??'Sistem','notes'=>$e->notes,'created_at'=>$e->created_at?->toIso8601String()])->values(),'permissions'=>['can_decide'=>$approval->status===ApprovalStatus::Pending,'own_request'=>$approval->requested_by===$request->user()->id]]]);}
public function approve(Request $request,ApprovalRequest $approval,ApprovalEngine $engine):JsonResponse{$this->authorizeAccess($request);$data=$request->validate(['notes'=>['nullable','string','max:2000']]);$engine->approve($approval,$request->user(),$data['notes']??null);return response()->json(['message'=>'Permintaan telah disetujui dan tindakan diterapkan.']);}
public function reject(Request $request,ApprovalRequest $approval,ApprovalEngine $engine):JsonResponse{$this->authorizeAccess($request);$data=$request->validate(['notes'=>['required','string','min:5','max:2000']]);$engine->reject($approval,$request->user(),$data['notes']);return response()->json(['message'=>'Permintaan telah ditolak.']);}
private function authorizeAccess(Request $request):void{abort_unless($request->user()->isStaff()&&$request->user()->tokenCan('staff:approvals')&&$request->user()->hasRole('owner','admin'),403);}
private function summary(ApprovalRequest $a):array{return ['id'=>$a->id,'request_number'=>$a->request_number,'type'=>['code'=>$a->type->value,'label'=>$a->type->label()],'status'=>['code'=>$a->status->value,'label'=>$a->status->label()],'requester'=>$a->requester?->name,'decider'=>$a->decider?->name,'requested_at'=>$a->requested_at?->toIso8601String(),'expires_at'=>$a->expires_at?->toIso8601String(),'decided_at'=>$a->decided_at?->toIso8601String(),'reference'=>$a->refund?->sale?->invoice_number,'amount'=>$a->refund?->amount??0];}}