@extends('layouts.app')
@section('content')
<div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold text-brand-700">KATALOG & INVENTORY</p><h1 class="mt-1 text-3xl font-black text-ink-900">Produk dan stok</h1></div><form><input name="q" value="{{ request('q') }}" placeholder="Cari produk / SKU / barcode"></form></div>
<details class="card mt-6"><summary class="cursor-pointer font-black text-ink-900">+ Tambah produk</summary><form method="post" action="{{ route('products.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@csrf
    <div class="grid gap-1"><label>Nama</label><input name="name" required></div><div class="grid gap-1"><label>SKU</label><input name="sku" required></div><div class="grid gap-1"><label>Barcode</label><input name="barcode"></div><div class="grid gap-1"><label>Satuan</label><input name="unit" value="pcs" required></div>
    <div class="grid gap-1"><label>Kategori</label><select name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="grid gap-1"><label>Supplier</label><select name="supplier_id"><option value="">Tidak ada</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></div><div class="grid gap-1"><label>Harga modal</label><input name="cost_price" type="number" min="0" required></div><div class="grid gap-1"><label>Harga jual</label><input name="selling_price" type="number" min="0" required></div>
    <div class="grid gap-1"><label>Stok minimum</label><input name="minimum_stock" type="number" min="0" value="5" required></div><div class="grid gap-1"><label>Lokasi rak</label><input name="shelf_location"></div><input type="hidden" name="is_active" value="1"><div class="flex items-end"><button class="btn-primary">Simpan produk</button></div>
</form></details>
<div class="table-wrap mt-6"><table class="data-table"><thead><tr><th>Produk</th><th>Kategori</th><th>Harga</th><th>Stok</th><th>Penyesuaian stok</th></tr></thead><tbody>@forelse($products as $product)<tr><td><strong>{{ $product->name }}</strong><p class="text-xs text-slate-500">{{ $product->sku }} · {{ $product->barcode ?: 'tanpa barcode' }}</p></td><td>{{ $product->category->name }}</td><td><strong>Rp {{ number_format($product->selling_price,0,',','.') }}</strong><p class="text-xs text-slate-500">Modal Rp {{ number_format($product->cost_price,0,',','.') }}</p></td><td><span class="badge {{ $product->isLowStock() ? 'bg-red-100 text-red-700' : 'bg-emerald-100 text-emerald-700' }}">{{ $product->stock }} {{ $product->unit }}</span><p class="mt-1 text-xs text-slate-500">Min. {{ $product->minimum_stock }}</p></td><td><form method="post" action="{{ route('products.stock',$product) }}" class="flex min-w-[360px] gap-2">@csrf<input class="w-24" name="quantity" type="number" placeholder="+/-" required><select name="type"><option value="purchase">Stok masuk</option><option value="adjustment">Penyesuaian</option><option value="damaged">Rusak</option><option value="lost">Hilang</option><option value="internal_use">Internal</option></select><input name="reason" placeholder="Alasan" required><button class="btn-secondary">Simpan</button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-slate-500">Belum ada produk.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $products->links() }}</div>
@endsection
