@extends('layouts.app')
@section('content')
@if($canBootstrapOwner)
    <div class="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">
        <strong>Lengkapi kontrol dua owner.</strong> Sistem saat ini hanya memiliki satu owner aktif. Buat pegawai dengan role Owner; permintaan tersebut dapat disetujui sekali oleh owner saat ini untuk membuka alur persetujuan terpisah.
    </div>
@endif
<div><p class="text-sm font-bold text-brand-700">AKSES & KEAMANAN</p><h1 class="mt-1 text-3xl font-black text-ink-900">Pegawai</h1><p class="mt-1 text-sm text-slate-500">Role hanya dapat diberikan oleh server melalui halaman owner ini.</p></div>
<details class="card mt-6"><summary class="cursor-pointer font-black">+ Buat akun pegawai</summary><form method="post" action="{{ route('employees.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@csrf<div class="grid gap-1"><label>Nama</label><input name="name" required></div><div class="grid gap-1"><label>Email</label><input name="email" type="email" required></div><div class="grid gap-1"><label>Telepon</label><input name="phone"></div><div class="grid gap-1"><label>Role</label><select name="role">@foreach($roles as $role)<option value="{{ $role->value }}">{{ $role->label() }}</option>@endforeach</select></div><div class="grid gap-1"><label>Password (min. 12 karakter)</label><input name="password" type="password" required></div><div class="grid gap-1"><label>Konfirmasi password</label><input name="password_confirmation" type="password" required></div><div class="flex items-end"><button class="btn-primary">Buat akun</button></div></form></details>
<div class="table-wrap mt-6"><table class="data-table"><thead><tr><th>Pegawai</th><th>Role saat ini</th><th>Login terakhir</th><th>Ubah akses</th></tr></thead><tbody>@foreach($employees as $employee)<tr><td><strong>{{ $employee->name }}</strong><p class="text-xs text-slate-500">{{ $employee->email }}</p></td><td><span class="badge">{{ $employee->role->label() }}</span></td><td>{{ $employee->last_login_at?->diffForHumans() ?? 'Belum pernah' }}</td><td><form method="post" action="{{ route('employees.update',$employee) }}" class="flex min-w-[320px] items-center gap-2">@csrf @method('put')<select name="role">@foreach(\App\Enums\UserRole::cases() as $role)@if($role !== \App\Enums\UserRole::Customer)<option value="{{ $role->value }}" @selected($employee->role===$role)>{{ $role->label() }}</option>@endif @endforeach</select><select name="is_active"><option value="1" @selected($employee->is_active)>Aktif</option><option value="0" @selected(!$employee->is_active)>Nonaktif</option></select><button class="btn-secondary">Simpan</button></form></td></tr>@endforeach</tbody></table></div><div class="mt-4">{{ $employees->links() }}</div>
@endsection
