@extends('layouts.app')
@section('content')
<div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('orders.index') }}" class="text-sm font-bold text-brand-700">← Kembali</a><p class="mt-3 text-sm font-bold text-slate-400">{{ $order->order_number }}</p><h1 class="mt-1 text-3xl font-black text-ink-900">{{ $order->customer_name }} · {{ ucfirst($order->type) }}</h1></div><span class="badge bg-emerald-100 text-emerald-800">{{ $order->status->label() }}</span></div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]">
    <div class="space-y-6"><section class="card"><h2 class="text-lg font-black text-ink-900">Detail pekerjaan</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-xs font-bold uppercase text-slate-400">Kontak</dt><dd class="mt-1 font-semibold">{{ $order->customer_phone }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Layanan</dt><dd class="mt-1 font-semibold">{{ $order->service?->name ?? ucfirst($order->type) }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Deadline</dt><dd class="mt-1 font-semibold">{{ $order->deadline_at?->format('d M Y H:i') ?? 'Belum ditentukan' }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Ditugaskan kepada</dt><dd class="mt-1 font-semibold">{{ $order->assignee?->name ?? 'Belum ditugaskan' }}</dd></div></dl><div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm whitespace-pre-line">{{ $order->notes ?: 'Tidak ada catatan.' }}</div></section>
        @if($canAccessFiles)
            <section class="card"><h2 class="text-lg font-black text-ink-900">File privat</h2><div class="mt-4 space-y-2">@forelse($order->files as $file)<a class="flex items-center justify-between rounded-xl border border-slate-200 p-3 hover:border-brand-500" href="{{ URL::temporarySignedRoute('orders.files.download', now()->addMinutes(10), [$order,$file]) }}"><div><p class="font-bold">{{ $file->original_name }}</p><p class="text-xs text-slate-500">{{ $file->mime_type }} · {{ number_format($file->size/1024,1) }} KB</p></div><span class="text-sm font-bold text-brand-700">Unduh</span></a>@empty<p class="text-sm text-slate-500">Tidak ada file.</p>@endforelse</div></section>
        @else
            <section class="card border-amber-200 bg-amber-50"><h2 class="text-lg font-black text-amber-950">File privat dibatasi</h2><p class="mt-2 text-sm leading-6 text-amber-900">File hanya dapat diakses owner, admin, atau pegawai yang ditugaskan sesuai jenis pekerjaan.</p></section>
        @endif
        @can('manageFinancials', $order)
            <section class="card"><h2 class="text-lg font-black text-ink-900">Harga, pembayaran & penugasan</h2><form method="post" action="{{ route('orders.details.update', $order) }}" class="mt-4 grid gap-4 sm:grid-cols-2">@csrf @method('patch')<div><label>Estimasi</label><input class="mt-1 w-full" name="estimated_price" type="number" min="0" value="{{ old('estimated_price', $order->estimated_price) }}"></div><div><label>Harga akhir</label><input class="mt-1 w-full" name="final_price" type="number" min="0" value="{{ old('final_price', $order->final_price) }}"></div><div><label>Terbayar terverifikasi</label><input class="mt-1 w-full" name="paid_amount" type="number" min="0" value="{{ old('paid_amount', $order->paid_amount) }}" required></div><div><label>Deadline</label><input class="mt-1 w-full" name="deadline_at" type="datetime-local" value="{{ old('deadline_at', $order->deadline_at?->format('Y-m-d\TH:i')) }}"></div><div class="sm:col-span-2"><label>Pegawai yang ditugaskan</label><select class="mt-1 w-full" name="assigned_to"><option value="">Belum ditugaskan</option>@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected((string) old('assigned_to', $order->assigned_to) === (string) $assignee->id)>{{ $assignee->name }} · {{ $assignee->role->label() }}</option>@endforeach</select></div>@if($order->payment_confirmation_at)<p class="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900 sm:col-span-2">Pelanggan mengonfirmasi pembayaran melalui <strong>{{ $order->payment_confirmation_method }}</strong> {{ $order->payment_confirmation_reference ? 'dengan referensi '.$order->payment_confirmation_reference : '' }} pada {{ $order->payment_confirmation_at->format('d M Y H:i') }}. Cocokkan mutasi sebelum mengubah nominal terbayar.</p>@endif<button class="btn-primary sm:col-span-2">Simpan detail</button></form></section>
        @endcan
        @can('uploadResult', $order)
            <section class="card"><h2 class="text-lg font-black text-ink-900">Unggah file hasil</h2><p class="mt-2 text-xs leading-5 text-slate-500">File disimpan privat. Pelanggan baru dapat mengunduhnya setelah pembayaran terverifikasi lunas dan status siap atau selesai.</p><form method="post" action="{{ route('orders.results.store', $order) }}" enctype="multipart/form-data" class="mt-4 flex flex-col gap-3 sm:flex-row">@csrf<input name="file" type="file" required class="flex-1"><button class="btn-primary">Unggah hasil</button></form></section>
        @endcan
        <section class="card"><h2 class="text-lg font-black text-ink-900">Riwayat status</h2><ol class="mt-4 space-y-4">@foreach($order->statusHistories->sortByDesc('created_at') as $history)<li class="border-l-2 border-brand-500 pl-4"><p class="font-bold">{{ str($history->to_status)->replace('_',' ')->title() }}</p><p class="text-xs text-slate-500">{{ $history->created_at->format('d M Y H:i') }} · {{ $history->user?->name ?? 'Sistem/pelanggan' }}</p>@if($history->notes)<p class="mt-1 text-sm">{{ $history->notes }}</p>@endif</li>@endforeach</ol></section>
    </div>
    <aside class="card h-fit xl:sticky xl:top-5"><h2 class="text-lg font-black text-ink-900">Perbarui status</h2>@if($order->status->allowedTransitions())<form method="post" action="{{ route('orders.status',$order) }}" class="mt-4 grid gap-3">@csrf<label>Status berikutnya</label><select name="status">@foreach($order->status->allowedTransitions() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select><label>Catatan</label><textarea name="notes" rows="3"></textarea><button class="btn-primary">Simpan perubahan</button></form>@else<p class="mt-3 text-sm text-slate-500">Pesanan telah mencapai status akhir.</p>@endif<div class="mt-6 border-t border-slate-200 pt-4"><p class="text-xs font-bold uppercase text-slate-400">Tautan pelacakan</p><code class="mt-2 block break-all rounded-xl bg-slate-100 p-3 text-xs">{{ route('public.track.show',$order->public_token) }}</code></div></aside>
</div>
@endsection
